# See https://www.git-town.com/configuration-file for details

[branches]
main = "main"
feature-regex = "^users/SirDue/.*"
unknown-type = "prototype"

[hosting]
origin-hostname = "github.com"

[ship]
delete-tracking-branch = true
strategy = "api"
