name: Git Town

on:
  pull_request:
    branches:
      - '**'

jobs:
  git-town:
    name: Display the branch stack
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: git-town/action@v1
        with:
          location: comment
